### PR TITLE
[WIP] Release 2.0.0

### PR DESCRIPTION
**Pull request by robdmoore**
Work in progress pull request for the 2.0.0 release. This release will have two major features:

* New list builder syntax that obviates the need for `.With` i.e. you can do `.TheFirst(2).WithFirstName("Rob").TheNext(3).WithLastName("Davies")`
* Anonymous value generation and equivalence classes as a first class concept (along with conventions) to allow you to get up and running with builders that generate meaningful data very quickly (and when you generate lists of objects they will all have different values by default)

todo:

- [x] Get rid of NBuilder in favour of a better syntax
- [x] Anonymous value generation and equivalence classes as first class concept
- [x] `Any.StringEndingWith()`, `Any.Integer()`, `Any.PositiveInteger()`, `Any.NegativeInteger()`
- [x] `Any.Of<TEnumType>(params TEnumType[] include = null)`, `Any.Enum<TEnumType>(TEnumType[] except = null)` ...
- [ ] Dependent properties (e.g. Address.Line1, Address.Line2)
- [ ] Automatically build an object by reflecting for a constructor with the most params and getting each by looking for a property of the same name - use AutoFixture if it can't be done or maybe throw an exception?
- [ ] Nested property name support
- [ ] Nested construction support?
- [ ] Implicit conversion?
- [ ] Reference a builder class to get objects of that type anonymously built using the builder
- [ ] Add anonymous value providers e.g.first names, email addresses, etc.
- [ ] Pick syntax from NBuilder
- [ ] Random and Section from NBuilder

This post gives a really good overview of the extensibility in AutoFixture. http://stackoverflow.com/questions/22331791/applying-dry-to-autofixture-build-statements

### CODE REVIEW

**Comment by robdmoore** [comment]
For anyone playing at home I'm going to test this out on one of my projects to make sure it's all good and the pain of upgrading a codebase is acceptable. If I'm happy then I'm going to ship this and move all the other todo items into up-for-grabs issues.

**Comment by robdmoore** [comment]
Note to self: IL-merge Castle.Core

**Comment by Quantumplation** [comment]
Do you have an example of this at work in a real project? I'd really love to see how it impacts things, but i'm having a hard time getting a good impression from the unit tests.

**Comment by robdmoore** [comment]
Superceeded by #22

**Comment by robdmoore** [comment]
@Quantumplation see http://robdmoore.id.au/blog/2015/04/22/announcing-teststack-dossier-library/

**Pull request closed without merging**
